### ISSUE TITLE
7. Deploy Rancher to bastion-host.

### ISSUE THREAD

**Issue by lalekilic** [fuchicorp/main#261]
We need to install Rancher UI, here's the documentation I am following!

Happy Ranching!

Thanks!
Lale 

https://github.com/fuchicorp/cluster-infrastructure/wiki/Deploying-Rancher-UI

**Comment by ksalrin** [comment]
Please provide url or screenshot of the Rancher login screen.  Also please move these tickets to "Review" not "Done".  I was not able to review these because they were no in the right column.

**Comment by lalekilic** [comment]
<img width="1333" alt="Screen Shot 2021-08-29 at 10 13 32 AM" src="https://user-images.githubusercontent.com/79033140/131255527-e7951d02-7b88-46bc-b5dc-d2383a1cb09d.png">
