### ISSUE TITLE
6. Deploy ELK-Stack to bastion-host 

### ISSUE THREAD

**Issue by lalekilic** [fuchicorp/main#270]
We are going to deploy ELK-Stack to our bastion-host so we can understand how it works. Here's the Github repo with documentation to follow!

https://github.com/fuchicorp/elk-stack

Thanks!
Lale

**Comment by ksalrin** [comment]
Please provide screen shot of Kibana and Elastic Search

**Comment by ksalrin** [comment]
Also you need to move this to "Review" not "Done"

**Comment by lalekilic** [comment]
<img width="1321" alt="Screen Shot 2021-08-29 at 10 13 51 AM" src="https://user-images.githubusercontent.com/79033140/131255695-5409695c-b3f0-4efc-8cf5-f9ce51897ec0.png">

**Comment by lalekilic** [comment]
<img width="504" alt="Screen Shot 2021-08-29 at 10 18 09 AM" src="https://user-images.githubusercontent.com/79033140/131255701-f2be2a2b-fe09-4764-afeb-0280b1e493b1.png">
