### ISSUE TITLE
ELK

### ISSUE THREAD

**Issue by victoryyyyyy** [fuchicorp/main#277]
Deploying ELK using the following documentation:

https://github.com/fuchicorp/elk-stack

**Comment by victoryyyyyy** [comment]
https://kibana.capturedbyvictory.com/app/kibana#/home
https://elasticsearch.capturedbyvictory.com/

**Comment by ksalrin** [comment]
I cannot see cause I'm not whitelisted.  Could you take a screenshot of both and put it in here for me to see?

**Comment by victoryyyyyy** [comment]
![2021-08-30 (2)](https://user-images.githubusercontent.com/79341147/131377652-ebeab903-b7dd-485e-b95c-ce91d9000690.png)
![2021-08-30](https://user-images.githubusercontent.com/79341147/131377655-db2dd312-42f8-4acb-8d52-abca7c6db05b.png)
