### ISSUE TITLE
Deploy an Application with Jenkins

### ISSUE THREAD

**Issue by balkhibayeva** [fuchicorp/main#289]
Hello!

Please deploy your choice of ONE application to all environments (DEV, QA, STAGE and PROD) with Jenkins.  You will need to dockerize, create a helm chart, terraform module and lastly Jenkins groovy files for your application. Please see more steps and repo below. 

**App Repo:** 
https://github.com/fuchicorp/apps

**Steps:**
- Go to the App Repo above and clone it
- Choose ONE application you would like to deploy. (barter, cramis, food-market, json-viewer, node-hello, or react-hello)
- Create your own PRIVATE repo on your github account.  Copy over the ONE application folder you will be working with. 
- Dockerize the files in that folder
- Build and test your image
- Create a helm chart to deploy your application. Deploy and ensure it works correctly and you can view the image at the URL you specified.
- Create a terraform module and ensure the helm chart is soft coded to pass values to the helm chart. 
- Lastly, use the groovy files from hello-world to help create pipelines and deploy your application with your Jenkins.
- Deploy your application with Jenkins to all environments (DEV, QA, STAGE and PROD).  Ensure you can view them all. 
- Once this is complete, provide your URL to your application in your ticket for instructors to check.  

**Helpful Videos:**
Hello-world deployment: https://academy.fuchicorp.com/videos/folders/watch/af0208a2a6b38a23cd2252e7f555b667e2440561

**Comment by balkhibayeva** [comment]
Getting error when running Jenkins deploy job:
I run kubectl describe pods -n dev 
 Error: InvalidImageName
  Warning  InspectFailed  60s (x13710 over 2d1h)    kubelet, gke-fuchicorp-cluster-default-pool-a70c7ef2-9qtj  Failed to apply default image tag "docker.ainurgcp.com/": couldn't parse image reference "docker.ainurgcp.com/": invalid reference format

**Comment by ksalrin** [comment]
I'm not sure why there is an issue.  I ran your master job as is and it was successful.  Please check and create your other branches. Please make sure you are building from build to deploy, not just trying to use deploy pipeline only to deploy to other environments.

**Comment by balkhibayeva** [comment]
Unable to build qa branch. Error received:

 [1m[31mError: [0m[0m[1mError asking for user input: 1 error occurred:
11:38:04  	* module.food-market.data.template_file.chart_values_template: configuration for module.food-market.provider.template is not present; a provider configuration block is required for all operations

**Comment by ksalrin** [comment]
Messaged you on slack.  I went to your Jenkins to take a look but your food-market pipelines weren't there.  You redoing them?

**Comment by ksalrin** [comment]
Please add the app urls for me to check

**Comment by balkhibayeva** [comment]
https://food-market.ainurgcp.com/
