### ISSUE TITLE
Deploy application with Jenkins

### ISSUE THREAD

**Issue by pylypvl** [fuchicorp/main#294]
Hello!

Please deploy your choice of ONE application to all environments (DEV, QA, STAGE and PROD) with Jenkins. You will need to dockerize, create a helm chart, terraform module and lastly Jenkins groovy files for your application. Please see more steps and repo below.

Repo:
https://github.com/fuchicorp/apps

Steps:

Go to the App Repo above and clone it
Choose ONE application you would like to deploy. (barter, cramis, food-market, json-viewer, node-hello, or react-hello)
Create your own PRIVATE repo on your github account. Copy over the ONE application folder you will be working with.
Dockerize the files in that folder
Build and test your image
Create a helm chart to deploy your application. Deploy and ensure it works correctly and you can view the image at the URL you specified.
Create a terraform module and ensure the helm chart is soft coded to pass values to the helm chart.
Lastly, use the groovy files from hello-world to help create pipelines and deploy your application with your Jenkins.
Deploy your application with Jenkins to all environments (DEV, QA, STAGE and PROD). Ensure you can view them all.
Once this is complete, provide your URL to your application in your ticket for instructors to check.

**Comment by pylypvl** [comment]
![prod](https://user-images.githubusercontent.com/86280296/131198627-b51bfbe6-e865-46dd-8a0d-a47f9aceab9e.png)
![dev](https://user-images.githubusercontent.com/86280296/131198628-6fba6525-c6be-4367-9182-56877e1d255e.png)
![qa](https://user-images.githubusercontent.com/86280296/131198629-d424606c-0eed-4580-b8b9-b563137165cb.png)
![stage](https://user-images.githubusercontent.com/86280296/131198631-abf5229f-3841-4d53-bb91-faa371cb27ec.png)

**Comment by pylypvl** [comment]
https://dev.food-market.uraniium.com/
https://qa.food-market.uraniium.com/
https://stage.food-market.uraniium.com/
https://prod.food-market.uraniium.com/

**Comment by ksalrin** [comment]
Prod should not have prod in the URL.  Prod goes to the end user so it would food-market.uraniium.com.  Please correct and redeploy the release.

**Comment by pylypvl** [comment]
![prod](https://user-images.githubusercontent.com/86280296/131386133-79b8b282-b7b4-4e8a-845e-8e4c492e9927.png)

changed!

**Comment by pylypvl** [comment]
https://food-market.uraniium.com/
prod!
