### ISSUE TITLE
ELK Deployment

### ISSUE THREAD

**Issue by Jovanny159** [fuchicorp/main#310]
Terraform module for ELK
To be able to use following terraform module please follow the documentation.

Requirements
Terraform >= 0.11.14
Helm >=2.8.0 and <3.0.0
Kubernetes >=1.9
You should have an access to your Kubernetes cluster

**Comment by Jovanny159** [comment]
https://kibana.awsclassacademy.com/app/kibana#/home

**Comment by ksalrin** [comment]
I am not whitelisted so I cannot access URL.  Please add a screen shot of the ELK for me to see.

**Comment by Jovanny159** [comment]
<img width="1440" alt="Screen Shot 2021-08-30 at 5 33 39 PM" src="https://user-images.githubusercontent.com/79174883/131414492-0a4fb97f-6fe7-46e0-8779-599a2ba8bb90.png">
