### ISSUE TITLE
 ELK Deployment

### ISSUE THREAD

**Issue by emilbek-abdyrazakov** [fuchicorp/main#314]
Deploy ELK

**requirements**

    Terraform >= 0.11.14
    Helm >=2.8.0 and <3.0.0
    Kubernetes >=1.9
    You should have an access to your Kubernetes cluster

useful links

https://github.com/fuchicorp/elk-stack

Thanks 
Kelly

**Comment by ksalrin** [comment]
Please provide a screen shot of Kibana and Elastic search for me to see.

**Comment by emilbek-abdyrazakov** [comment]
<img width="1409" alt="Screen Shot 2021-08-29 at 12 37 05 PM" src="https://user-images.githubusercontent.com/79775583/131259936-ef3a28e1-b51d-4484-8292-218339ad45ca.png">
<img width="1431" alt="Screen Shot 2021-08-29 at 12 36 43 PM" src="https://user-images.githubusercontent.com/79775583/131259938-0064e7ef-3b0e-4357-99e0-fe17e6259273.png">
