### ISSUE TITLE
Deploy Rancher To Bastion Host 

### ISSUE THREAD

**Issue by musaevan** [fuchicorp/main#326]
Installing Rancher UI using the following documentation:

https://github.com/fuchicorp/cluster-infrastructure/wiki/Deploying-Rancher-UI

Here is the link for Rancher:
https://rancher.awsnazik.com/dashboard/c/local/explorer/namespace

<img width="752" alt="Screen Shot 2021-08-30 at 6 15 55 PM" src="https://user-images.githubusercontent.com/79178268/131417578-e638f81f-79a5-4569-bd37-3a25fbba5af6.png">

**Comment by ksalrin** [comment]
Please put a screen shot of the rancher logging screen or URL
