### ISSUE TITLE
Deployment of ELK-Stack to bastion-host

### ISSUE THREAD

**Issue by aikaburkan** [fuchicorp/main#329]
Deployment of  ELK-Stack to the bastion-host. 

Here's the Github repo with documentation to follow!

https://github.com/fuchicorp/elk-stack

**Comment by ksalrin** [comment]
Please provide a screen shot of Kibana and Elastic search for me to see.

**Comment by ksalrin** [comment]
Please provide a screen shot of Kibana and Elastic search for me to see.

**Comment by aikaburkan** [comment]
<img width="1440" alt="Screen Shot 2021-08-30 at 7 48 38 PM" src="https://user-images.githubusercontent.com/79178971/131423912-b7133d51-80f3-4173-98a2-1b84aea0da37.png">
<img width="1440" alt="Screen Shot 2021-08-30 at 7 48 57 PM" src="https://user-images.githubusercontent.com/79178971/131423929-b641aa84-ca1d-4e65-8d34-8fca742cc146.png">
