### ISSUE TITLE
Deploy ELK-Stack to bastion-host 

### ISSUE THREAD

**Issue by musaevan** [fuchicorp/main#335]
We are going to deploy ELK-Stack to our bastion-host so we can understand how it works. Here's the Github repo with documentation to follow!

https://github.com/fuchicorp/elk-stack

Thanks!

isitup link:
https://isitup.fuchicorp.com/services/awsnazik.com

kibana:
https://kibana.awsnazik.com/app/kibana#/home/tutorial_directory/sampleData

elasticsearch:
https://elasticsearch.awsnazik.com/

waypoint:
https://waypoint.awsnazik.com/auth

![Screen Shot 2021-08-29 at 2 04 34 PM](https://user-images.githubusercontent.com/79178268/131262379-f21a3326-1eb0-483a-8faf-bbb394d1dacd.png)

![Screen Shot 2021-08-29 at 2 04 58 PM](https://user-images.githubusercontent.com/79178268/131262388-a55472cc-42d2-4ec8-b86b-530f08f0e878.png)

![Screen Shot 2021-08-29 at 2 05 14 PM](https://user-images.githubusercontent.com/79178268/131262392-56842477-8733-47d2-9fc7-022eb6170f6f.png)

**Comment by ksalrin** [comment]
Please provide screenshot of Kibana and Elastic Search. I'm not whitelisted so I cannot access URL.
