### ISSUE TITLE
6. ELK Deployment

### ISSUE THREAD

**Issue by EHolovan** [fuchicorp/main#339]
Deploying ELK using the following documentation:

https://github.com/fuchicorp/elk-stack

**Comment by EHolovan** [comment]
https://kibana.best4aws.com/app/kibana#/home

https://elasticsearch.best4aws.com/

**Comment by ksalrin** [comment]
Can you add screenshots?  I cannot access because I'm not whitelisted.

**Comment by EHolovan** [comment]
![image](https://user-images.githubusercontent.com/79173750/131580893-3dbe6e79-b8c4-4ab9-93af-7deaf02e7fcc.png)

**Comment by EHolovan** [comment]
![image](https://user-images.githubusercontent.com/79173750/131580998-923dd6e5-53b8-4a07-b550-c0848bc0820d.png)
