### ISSUE TITLE
1. Deploy cluster to your own GCP account

### ISSUE THREAD

**Issue by ksalrin** [fuchicorp/main#364]
Welcome to FuchiCorp!  Please build your own cluster first and on top of that, you will need to deploy common tools. Please follow the README.md documentation of cluster infrastructure and deploy the cluster.

**Documentation for cluster deployment:**
https://github.com/fuchicorp/cluster-infrastructure/tree/master/kube-cluster

**Video to deploy cluster:**
https://academy.fuchicorp.com/videos/folders/watch/dc0b53a5d46e17a57e9a127756759dd9309b59b4

**Comment by fuchicorp-manage** [comment]
Confirmed
