### ISSUE TITLE
Deploy application with Jenkins!

### ISSUE THREAD

**Issue by mirlan88** [fuchicorp/main#369]
Hello!

Please deploy your choice of ONE application to all environments (DEV, QA, STAGE and PROD) with Jenkins. You will need to dockerize, create a helm chart, terraform module and lastly Jenkins groovy files for your application. Please see more steps and repo below.

App Repo:
https://github.com/fuchicorp/apps

Steps:

Go to the App Repo above and clone it
Choose ONE application you would like to deploy. (barter, cramis, food-market, json-viewer, node-hello, or react-hello)
Create your own PRIVATE repo on your github account. Copy over the ONE application folder you will be working with.
Dockerize the files in that folder
Build and test your image
Create a helm chart to deploy your application. Deploy and ensure it works correctly and you can view the image at the URL you specified.
Create a terraform module and ensure the helm chart is soft coded to pass values to the helm chart.
Lastly, use the groovy files from hello-world to help create pipelines and deploy your application with your Jenkins.
Deploy your application with Jenkins to all environments (DEV, QA, STAGE and PROD). Ensure you can view them all.
Once this is complete, provide your URL to your application in your ticket for instructors to check.
Helpful Videos:
Hello-world deployment: https://academy.fuchicorp.com/videos/folders/watch/af0208a2a6b38a23cd2252e7f555b667e2440561
https://github.com/mirlan88/food-market

**Comment by ksalrin** [comment]
what issue are you having?

**Comment by mirlan88** [comment]
11:45:09  1 error occurred:
11:45:09  	* module.academy-deploy.helm_release.helm_deployment: 1 error occurred:
11:45:09  	* helm_release.helm_deployment: template: food-market/templates/service.yaml:4:11: executing "food-market/templates/service.yaml" at <include "food-market.fullname" .>: error calling include: template: no template "food-market.fullname" associated with template "gotpl"
11:45:09  
11:45:09  
11:45:09  
11:45:09  
11:45:09  
11:45:09  Terraform does not automatically rollback in the face of errors.
11:45:09  Instead, your Terraform state file has been partially updated with
11:45:09  any resources that successfully completed. Please address the error
11:45:09  above and apply again to incrementally change your infrastructure.[0m
11:45:09  
11:45:09  [0m[0m[0m
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] echo
script returned exit code 1
[Pipeline] container
[Pipeline] {
[Pipeline] writeFile
[Pipeline] sh
+ gcloud auth activate-service-account --key-file=/etc/secrets/service-account/credentials.json
Activated service account credentials for: [common-service-account@optimal-iris-323020.iam.gserviceaccount.com]
+ gsutil cp current-job.log gs://fuchicorp-first/JENKINS_LOGS/food-market-deploy/2021-09-07/food-market-deploy-2021-09-07-2.txt
Copying file://current-job.log [Content-Type=application/octet-stream]...
/ [0 files][    0.0 B/ 16.3 KiB]                                                
/ [1 files][ 16.3 KiB/ 16.3 KiB]                                                
Operation completed over 1 objects/16.3 KiB.                                     
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline
Finished: FAILURE

**Comment by ksalrin** [comment]
what are the urls for your food-market for me to check?

**Comment by mirlan88** [comment]
https://github.com/mirlan88/food-market

**Comment by mirlan88** [comment]
https://stage.food-market.mirtynyc.com/
https://dev.food-market.mirtynyc.com/
https://qa.food-market.mirtynyc.com/
https://food-market.mirtynyc.com/
