### ISSUE TITLE
Deploy an Application with Jenkins

### ISSUE THREAD

**Issue by Adamisaeva** [fuchicorp/main#381]
Please deploy your choice of ONE application to all environments (DEV, QA, STAGE and PROD) with Jenkins. You will need to dockerize, create a helm chart, terraform module and lastly Jenkins groovy files for your application .
Steps:
- Go to the App Repo https://github .com/fuchicorp/apps and clone it
- Choose ONE application (barter, cramis, food-market, json-viewer, node-hello, or react-hello)
- Create your own PRIVATE repo on your github account . Copy ONE application folder from app repo to your repo . - Dockerize the files in that folder. Build and test that docker image
- Create a helm chart to deploy your application . Deploy and ensure it works correctly and you can view the image at the URL you specified.
- Create a terraform module and ensure the helm chart is soft coded .
- Use the groovy files from hello-world to help create pipelines and deploy your application with your Jenkins. - Deploy your application with Jenkins to all environments (DEV, QA, STAGE and PROD) .
- Once this is complete, provide your URLs to your application in your ticket for instructors to check . Helpful Videos:
Hello-world deployment: https://academy .fuchicorp .com/videos/folders/watch/ af0208a2a6b38a23cd2252e7f555b667e2440561

**Comment by Adamisaeva** [comment]
<img width="991" alt="Screen Shot 2021-10-29 at 2 50 45 PM" src="https://user-images.githubusercontent.com/80854160/139507138-04e45e92-a4b3-40c0-85ea-350dad303e9f.png">

**Comment by Adamisaeva** [comment]
I did run helm3 install my barter app, but my pod is ImagePullBackOff. The image was supposed to be pulled from Nexus.

**Comment by Adamisaeva** [comment]
<img width="1126" alt="Screen Shot 2021-10-29 at 5 23 35 PM" src="https://user-images.githubusercontent.com/80854160/139507698-d0269b57-baf4-4b3a-8e8a-f9f9ed7ab6a5.png">

**Comment by Adamisaeva** [comment]
This is what i have when i describe the pod

**Comment by ksalrin** [comment]
can you show me your docker file?

**Comment by Adamisaeva** [comment]
<img width="1344" alt="Screen Shot 2021-11-03 at 5 13 03 PM" src="https://user-images.githubusercontent.com/80854160/140200581-8e950216-cba5-4686-983c-97b80c50d86e.png">

**Comment by Adamisaeva** [comment]
Having this when i try to deploy to Prod...

**Comment by Adamisaeva** [comment]
<img width="1309" alt="Screen Shot 2021-11-03 at 5 15 59 PM" src="https://user-images.githubusercontent.com/80854160/140200874-7f849843-336a-4299-8f56-d3f282f392b2.png">

**Comment by Adamisaeva** [comment]
This i Have, when i try to deploy to dev environment.

**Comment by Adamisaeva** [comment]
<img width="1344" alt="Screen Shot 2021-11-03 at 5 13 03 PM" src="https://user-images.githubusercontent.com/80854160/140214045-7c5a385f-11cb-4849-a40b-2c3cf27a3f56.png
<img width="1012" alt="Screen Shot 2021-11-03 at 5 40 17 PM" src="https://user-images.githubusercontent.com/80854160/140214623-ffd84723-0823-4555-81e7-24416957258e.png">
">

**Comment by Adamisaeva** [comment]
dev.barter.missadam.com
qa.barter.missadam.com
stage.barter.missadam.com
barter.missadam.com

**Comment by Adamisaeva** [comment]
[https://dev.barter.missadam.com/](url) 
[https://qa.barter.missadam.com/](url)
[https://stage.barter.missadam.com/](url)
[https://barter.missadam.com/](url)

**Comment by Adamisaeva** [comment]
https://dev.barter.missadam.com
https://qa.barter.missadam.com
https://stage.barter.missadam.com
https://barter.missadam.com

**Comment by Adamisaeva** [comment]
https://dev.barter.missadam.com
https://qa.barter.missadam.com
https://stage.barter.missadam.com
https://barter.missadam.com
