### ISSUE TITLE
DEPLOY COMMON TOOLS ON TOP OF YOUR CLUSTER

### ISSUE THREAD

**Issue by Iuliia16** [fuchicorp/main#394]
Please deploy common tools on top of your cluster and make sure all tools are deployed and up and 
running After you have deployed everything you can check isitup to verify
IsItUp link: https://isitup fuchicorp com/
Please watch this video:
https://academy fuchicorp com/videos/folders/watch/de409644e693eb3ca4386488164b1e3885efb0ba

**Comment by fuchicorp-manage** [comment]
Confirmed
