### ISSUE TITLE
Deploy an Application with Jenkins

### ISSUE THREAD

**Issue by ihoslav** [fuchicorp/main#470]
Please deploy your choice of ONE application to all environments (DEV, QA, STAGE and PROD) with Jenkins. 
You will need to dockerize, create a helm chart, terraform module and lastly Jenkins groovy files for your application. 

Steps:

- Go to the App Repo https://github.com/fuchicorp/apps and clone it
- Choose ONE application  (barter, cramis, food-market, json-viewer, node-hello, or react-hello)
- Create your own PRIVATE repo on your github account. Copy ONE application folder from app repo to your repo. 
- Dockerize the files in that folder. Build and test that docker image
- Create a helm chart to deploy your application. Deploy and ensure it works correctly and
   you can view the image at the URL you specified.
- Create a terraform module and ensure the helm chart is soft coded.
- Use the groovy files from hello-world to help create pipelines and deploy your application with your Jenkins.
- Deploy your application with Jenkins to all environments (DEV, QA, STAGE and PROD). 
- Once this is complete, provide your URLs to your application in your ticket for instructors to check
<img width="1104" alt="Screen Shot 2021-11-11 at 4 57 56 PM" src="https://user-images.githubusercontent.com/71399919/141514659-bbb67bcc-3e95-4c3e-b952-f6ba80857fee.png">
<img width="1104" alt="Screen Shot 2021-11-11 at 4 58 17 PM" src="https://user-images.githubusercontent.com/71399919/141514660-e3f0bd34-00fa-4e6e-a754-4cfe3c84b1f6.png">

**Comment by fuchicorp-manage** [comment]
Why we don't have any updates and moved to need help. What kind of help you need?
