### ISSUE TITLE
JENKINS HELLO WORLD BUILD AND DEPLOY

### ISSUE THREAD

**Issue by tobi1972** [fuchicorp/main#516]

**Comment by tobi1972** [comment]
![image](https://user-images.githubusercontent.com/72477807/140661937-2b9cea94-9c46-41b9-b639-d53055a7e332.png)
[](url)

**Comment by fuchicorp-manage** [comment]
Please update this ticket

**Comment by gulsenjm** [comment]
@tobi1972 can you please provide links of your application or screenshots?

**Comment by ksalrin** [comment]
This is showing that your whole cluster is not up.  Please check.
https://isitup.fuchicorp.com/services/derin2011.com

**Comment by fuchicorp-manage** [comment]
ticket is not ready to close it
