### ISSUE TITLE
 Deploy cluster to your own GCP account

### ISSUE THREAD

**Issue by emine1576** [fuchicorp/main#549]
Welcome to FuchiCorp! Please build your own cluster first and on top of that, 
you will need to deploy common tools. Please follow the README.md documentation 
of cluster infrastructure and deploy the cluster.

Documentation for cluster deployment:
https://github.com/fuchicorp/cluster-infrastructure/tree/master/kube-cluster

Video to deploy cluster:
https://academy.fuchicorp.com/videos/folders/watch/dc0b53a5d46e17a57e9a127756759dd9309b59b4

**Comment by fsadykov** [comment]
```
╭─emine1576@bastion-fuchicorp-com ~
╰─$ kubectl get nodes
NAME                                               STATUS   ROLES    AGE    VERSION
gke-fuchicorp-cluster-default-pool-56adb63a-k7tl   Ready    <none>   3h8m   v1.19.16-gke.1500
gke-fuchicorp-cluster-default-pool-56adb63a-l62m   Ready    <none>   3h8m   v1.19.16-gke.1500
gke-fuchicorp-cluster-default-pool-56adb63a-lg6g   Ready    <none>   3h8m   v1.19.16-gke.1500
```
