### ISSUE TITLE
3. JENKINS HELLO WORLD BUILD AND DEPLOY

### ISSUE THREAD

**Issue by sgasimov-dotcom** [fuchicorp/main#566]
Please deploy the hello-world application to DEV, QA, STAGE, PROD and TEST environments. You
will need to copy over the hello-world repo to your own PRIVATE repo. Then follow the videos and
documentation below to build and deploy with Jenkins.
Helpful Documentation:
https://github.com/fuchicorp/jenkins-global-library/blob/master/README.md
Videos:
https://academy.fuchicorp.com/videos/folders/watch/af0208a2a6b38a23cd2252e7f555b667e2440561
Clone Fuchicorp hello-world https://github.com/fuchicorp/hello-world
Create your own repo under your github account and clone to the bastion (make it PRIVATE PLEASE)
Copy all the files from Fuchicorp hello-world to your hello-world repo. Git add, commit and push.
Open your Jenkins (not fuchicorp’s) and follow the video to deploy

**Comment by sgasimov-dotcom** [comment]
I'm able to build hello-world-app image but receiving the below error when deploying.
I went through multiple video tutorials in Academy but couldn't figure out what is causing this error.


ERROR:

18:32:07  ##### Terraform Applying the Changes ####
[Pipeline] sh
18:32:08  Running set environment script!!
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] echo
script returned exit code 8
[Pipeline] container
[Pipeline] {
[Pipeline] writeFile
[Pipeline] sh
+ gcloud auth activate-service-account --key-file=/etc/secrets/service-account/credentials.json
Activated service account credentials for: [common-service-account@polar-processor-335305.iam.gserviceaccount.com]
+ gsutil cp current-job.log gs://fuchicorp-example-bucket12/JENKINS_LOGS/hello-world-deploy/2021-12-19/hello-world-deploy-2021-12-19-11.txt
Copying file://current-job.log [Content-Type=application/octet-stream]...
/ [0 files][    0.0 B/  8.4 KiB]                                                
/ [1 files][  8.4 KiB/  8.4 KiB]                                                
Operation completed over 1 objects/8.4 KiB.                                      
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline
Finished: FAILURE

**Comment by sgasimov-dotcom** [comment]
pls let me know if u need more details

**Comment by ksalrin** [comment]
https://jenkins.sgasimov.com/job/hello-world-deploy/13/console

I'm not sure where the issue was but I just built from the master and it was successful.  The only thing I can think of is that when you are building with parameters and selecting one of the check boxes.  Try deploying the dev environment and reach out to me if you are having further issues.

**Comment by sgasimov-dotcom** [comment]
> https://jenkins.sgasimov.com/job/hello-world-deploy/13/console
> 
> I'm not sure where the issue was but I just built from the master and it was successful. The only thing I can think of is that when you are building with parameters and selecting one of the check boxes. Try deploying the dev environment and reach out to me if you are having further issues.

It worked for the rest of them, thank you  Kelly
