### ISSUE TITLE
2)Deploy common tools on top of your cluster

### ISSUE THREAD

**Issue by mukhammadaziz16** [fuchicorp/main#581]
Please deploy common tools on top of your cluster and make sure all tools are deployed
and up and running. After you have deployed everything you can check isitup to verify

IsItUp link: https://isitup.fuchicorp.com/

Please watch this video:
https://academy.fuchicorp.com/videos/folders/watch/de409644e693eb3ca4386488164b1e3885efb0ba

**Comment by ksalrin** [comment]
Please see notes in Ticket 1. Once that is complete you can move this back to review.

**Comment by fsadykov** [comment]
For some reason the common tools is not showing up. Can we take a look this? Please let me know if you need help on this ticket

**Comment by mukhammadaziz16** [comment]
<img width="1676" alt="Screen Shot 2021-12-29 at 7 17 01 PM" src="https://user-images.githubusercontent.com/90929969/147714218-3e5c51ee-e6a2-4875-aff8-8f6c1fbf524b.png">
