### ISSUE TITLE
4.Deploy Bastion Host and test that all package are installed

### ISSUE THREAD

**Issue by Olesia87** [fuchicorp/main#589]
Please deploy your own bastion host following the instructions to build the packer image first. 
Please ensure all packages in the packer image are installed and working. This can be done by verifying the version.

Build Packer image first. Follow the README.md https://github.com/fuchicorp/bastion/blob/master/packer-scripts/README.md

Deploy your own Bastion with the Packer image you created. Follow the README.md 
https://github.com/fuchicorp/bastion/blob/master/README.md

Login into your bastion and verify packages are installed. Docker, Helm, Python, and Terraform.
Once verify your can destroy your bastion

Helpful link on how to access bastion host:
https://academy.fuchicorp.com/videos/folders/watch/f276205e8fc46b37534bb79a3409b9663066221a

**Comment by Olesia87** [comment]
![image](https://user-images.githubusercontent.com/84240252/147284889-ecb02e39-a068-4836-8b90-7063e1616a46.png)

**Comment by ksalrin** [comment]
please ssh into your bastion from the fuchicorp bastion.  This looks like your are doing from gcp console.

**Comment by Olesia87** [comment]
![image](https://user-images.githubusercontent.com/84240252/147432001-11393639-9de1-493d-9619-2544231dbf2e.png)

**Comment by fsadykov** [comment]
Hello @Olesia87,

Please take a screenshot of your bastion host not FuchiCorp please. Please let me know if you need any help with this ticket 

cc: @ksalrin  

Thank you

**Comment by Olesia87** [comment]
![image](https://user-images.githubusercontent.com/84240252/147581156-19b19443-be20-47d5-ad56-59f84074da9f.png)
