### ISSUE TITLE
6)ELK Deployment

### ISSUE THREAD

**Issue by mukhammadaziz16** [fuchicorp/main#596]
Please deploy ELK to your cluster. You will find the source code located in the Elk-stack repo in FuchiCorp:
https://github.com/fuchicorp/elk-stack. Please follow the README.md to deploy: https://github.com/fuchicorp/elk-stack/blob/master/README.md .

Once you have deployed successfully, please add screenshots of both Kibana and Elastic-search to 
the comments in your ticket for management approval.

**Comment by ksalrin** [comment]
Please provide screenshots of  both Kibana and Elasticsearch UIs for me to see.  I cannot view from isitup because my IP is not whitelisted for your applications. 

Thank you!

**Comment by mukhammadaziz16** [comment]
<img width="1115" alt="Screen Shot 2022-01-03 at 12 50 46 PM" src="https://user-images.githubusercontent.com/90929969/147968056-bb08c079-59c9-41d7-8cc7-b1bc2e54d3d4.png">
