### ISSUE TITLE
5. DEPLOY AN APPLICATION WITH JENKINS

### ISSUE THREAD

**Issue by sgasimov-dotcom** [fuchicorp/main#607]
Please deploy your choice of ONE application to all environments (DEV, QA, STAGE and PROD) with
Jenkins. You will need to dockerize, create a helm chart, terraform module and lastly Jenkins groovy files
for your application.
Steps:
- Go to the App Repo https://github.com/fuchicorp/apps and clone it
- Choose ONE application (barter, cramis, food-market, json-viewer, node-hello, or react-hello)
- Create your own PRIVATE repo on your github account. Copy ONE application folder from app repo to your repo.
- Dockerize the files in that folder. Build and test that docker image
- Create a helm chart to deploy your application. Deploy and ensure it works correctly and you can view
the image at the URL you specified.
- Create a terraform module and ensure the helm chart is soft coded.
- Use the groovy files from hello-world to help create pipelines and deploy your application with your Jenkins.
- Deploy your application with Jenkins to all environments (DEV, QA, STAGE and PROD).
- Once this is complete, provide your URLs to your application in your ticket for instructors to check.
Helpful Videos:
Hello-world deployment: https://academy.fuchicorp.com/videos/folders/watch/
af0208a2a6b38a23cd2252e7f555b667e2440561

**Comment by sgasimov-dotcom** [comment]
Currently having this issue when pushing Build in Jenkins

Dockerfile

FROM node:10.15-alpine
COPY . .
EXPOSE 3000
CMD [ "npm", "start" ]

Error:

[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // stage
[Pipeline] container
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Build docker image)
[Pipeline] isUnix
[Pipeline] sh
15:11:29  + docker build -t node-stage --build-arg 'environment=stage' --build-arg 'version=master' .
15:11:29  unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/jenkins/agent/workspace/node_master/deployments/docker/Dockerfile: no such file or directory
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] echo
script returned exit code 1
[Pipeline] container
[Pipeline] {
[Pipeline] writeFile
[Pipeline] sh
+ gcloud auth activate-service-account --key-file=/etc/secrets/service-account/credentials.json
Activated service account credentials for: [common-service-account@polar-processor-335305.iam.gserviceaccount.com]
+ gsutil cp current-job.log gs://fuchicorp-example-bucket12/JENKINS_LOGS/node/master/2021-12-21/node/master-2021-12-21-6.txt
Copying file://current-job.log [Content-Type=application/octet-stream]...
/ [0 files][    0.0 B/ 14.7 KiB]                                                
/ [1 files][ 14.7 KiB/ 14.7 KiB]                                                
Operation completed over 1 objects/14.7 KiB.                                     
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

Finished: FAILURE

**Comment by sgasimov-dotcom** [comment]
https://stage.nodehello.sgasimov.com/
https://dev.nodehello.sgasimov.com/
https://qa.nodehello.sgasimov.com/

**Comment by sgasimov-dotcom** [comment]
for some reason SSL cert doesn't appear on my pods..

![tls](https://user-images.githubusercontent.com/84157053/147032457-3c4e4002-9162-405c-8c0e-d88ae79fed61.jpg)

**Comment by sgasimov-dotcom** [comment]
after deploying node-hello it doesn't generate node-hello-tls  (SSL).
╰─$ kubectl get certs --all-namespaces 
```                                                                  1 ↵
NAMESPACE   NAME                       READY   SECRET                     AGE
dev         hello-world-tls            True    hello-world-tls            3d16h
elk         chart-elasticsearch-tls    True    chart-elasticsearch-tls    3d6h
elk         kibana-tls                 True    kibana-tls                 3d6h
prod        hello-world-tls            True    hello-world-tls            2d18h
qa          hello-world-tls            True    hello-world-tls            3d16h
stage       hello-world-tls            True    hello-world-tls            3d18h
tools       chart-sonarqube-tls        True    chart-sonarqube-tls        6d5h
tools       chart-vault-tls            True    chart-vault-tls            6d5h
tools       docker-tls                 True    docker-tls                 6d5h
tools       grafana-tls                True    grafana-tls                6d3h
tools       jenkins-letsencrypt-prod   True    jenkins-letsencrypt-prod   6d3h
tools       nexus-tls                  True    nexus-tls                  6d5h
tools       prometheus-server-tls      True    prometheus-server-tls      6d5h
```

I tried to destroy and re-deploy them with no luck . Tried deleting DNS pod.

After checking with Farkhod, putting this to Need Help. Thanks.

**Comment by sgasimov-dotcom** [comment]
Checked logs after deploying myip app , still not getting tls created 
```
time="2021-12-23T02:08:01Z" level=info msg="All records are already up to date"
time="2021-12-23T02:09:01Z" level=info msg="All records are already up to date"
time="2021-12-23T02:10:01Z" level=info msg="All records are already up to date"
time="2021-12-23T02:11:02Z" level=info msg="Change zone: cluster-infrastructure-zone batch #0"
time="2021-12-23T02:11:02Z" level=info msg="Add records: myip.sgasimov.com. A [35.197.45.198] 300"
time="2021-12-23T02:11:02Z" level=info msg="Add records: myip.sgasimov.com. TXT [\"heritage=external-dns,external-dns/owner=default,external-dns/resource=ingress/dev/myip-sgasimov\"] 300"
time="2021-12-23T02:12:01Z" level=info msg="All records are already up to date"
time="2021-12-23T02:13:02Z" level=info msg="All records are already up to date"
time="2021-12-23T02:14:01Z" level=info msg="All records are already up to date"
time="2021-12-23T02:15:01Z" level=info msg="All records are already up to date"
time="2021-12-23T02:16:01Z" level=info msg="All records are already up to date"

```


```
20:34
╰─$ kubectl get certs --all-namespaces
NAMESPACE   NAME                       READY   SECRET                     AGE
dev         hello-world-tls            True    hello-world-tls            3d19h
elk         chart-elasticsearch-tls    True    chart-elasticsearch-tls    3d10h
elk         kibana-tls                 True    kibana-tls                 3d10h
prod        hello-world-tls            True    hello-world-tls            2d22h
qa          hello-world-tls            True    hello-world-tls            3d19h
stage       hello-world-tls            True    hello-world-tls            3d21h
tools       chart-sonarqube-tls        True    chart-sonarqube-tls        6d8h
tools       chart-vault-tls            True    chart-vault-tls            6d8h
tools       docker-tls                 True    docker-tls                 6d8h
tools       grafana-tls                True    grafana-tls                6d6h
tools       jenkins-letsencrypt-prod   True    jenkins-letsencrypt-prod   6d7h
tools       nexus-tls                  True    nexus-tls                  6d8h
tools       prometheus-server-tls      True    prometheus-server-tls      6d8h
```

**Comment by sgasimov-dotcom** [comment]
After a cluster downgrade from 1.21 to 1.20, it started generating TLS as normal.
All seem good.

https://stage.nodehello.sgasimov.com/
https://dev.nodehello.sgasimov.com/
https://qa.nodehello.sgasimov.com/

Thank you.

**Comment by ksalrin** [comment]
Please send the prod url, its missing.

**Comment by sgasimov-dotcom** [comment]
PROD: https://nodehello.sgasimov.com/

**Comment by sgasimov-dotcom** [comment]
Food Market:

**stage**: https://stage.food-market.sgasimov.com/
**test**: https://test.food-market.sgasimov.com/
**food**: https://food-market.sgasimov.com/
**qa**: https://qa.food-market.sgasimov.com/
**dev**: https://dev.food-market.sgasimov.com/

**Comment by fsadykov** [comment]
Nice thank you @sgasimov-dotcom  I am closing this ticket for you
