### ISSUE TITLE
DEPLOY BASTION HOST AND TEST THAT ALL PACKAGE ARE INSTALLED

### ISSUE THREAD

**Issue by Atabek-cyber** [fuchicorp/main#616]
Please deploy your own bastion host following the instructions to build the packer image first. 
Please ensure all packages in the packer image are installed and working. This can be done by verifying the version.

Build Packer image first. Follow the README.md https://github.com/fuchicorp/bastion/blob/master/packer-scripts/README.md

Deploy your own Bastion with the Packer image you created. Follow the README.md 
https://github.com/fuchicorp/bastion/blob/master/README.md

Login into your bastion and verify packages are installed. Docker, Helm, Python, and Terraform.
Once verify your can destroy your bastion

Helpful link on how to access bastion host:
https://academy.fuchicorp.com/videos/folders/watch/f276205e8fc46b37534bb79a3409b9663066221a

**Comment by Atabek-cyber** [comment]
<img width="1124" alt="Screen Shot 2021-12-22 at 12 41 41 PM" src="https://user-images.githubusercontent.com/84157336/147140307-3419a05f-56c3-4971-b53b-9b45dbb276e6.png">

**Comment by ksalrin** [comment]
Please show a screenshot of you logged into your bastion from the terminal

**Comment by Atabek-cyber** [comment]
Hi there, you mean I should log in to the which I created bastion packer image from my VS or just log in to my bastion host

Atabek Bekenov

**Comment by Atabek-cyber** [comment]
<img width="1063" alt="Screen Shot 2021-12-22 at 4 30 40 PM" src="https://user-images.githubusercontent.com/84157336/147162406-6b8c4e9e-2ea9-400d-8502-c6e9f84a77cc.png">

**Comment by Atabek-cyber** [comment]
![Screen Shot 2021-12-23 at 1 42 56 PM](https://user-images.githubusercontent.com/84157336/147285424-b2cb6fdf-34a6-4a3b-bbec-48c1f907c3d8.png)
