### ISSUE TITLE
7. DEPLOY RANCHER

### ISSUE THREAD

**Issue by sgasimov-dotcom** [fuchicorp/main#629]
Deploy Rancher to your cluster. Please navigate to the common_tools repo and under charts you will
find the Rancher helm chart: https://github.com/fuchicorp/common_tools/tree/master/charts/rancher.
Please follow this wiki to help deploy:https://github.com/fuchicorp/common_tools/wiki/Deploying-
Rancher-Chart

**Comment by sgasimov-dotcom** [comment]
https://rancher.sgasimov.com/

**Comment by ksalrin** [comment]
The cert does not seem to be showing up.  Can you please take a look and troubleshoot.

**Comment by sgasimov-dotcom** [comment]
Getting this cert error while trying to re-deploy Rancher:

Error: failed to create resource: Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": no endpoints available for service "cert-manager-webhook"

**Comment by sgasimov-dotcom** [comment]
After re-building the cluster everything worked fine .

https://rancher.sgasimov.com/
