### ISSUE TITLE
2. Deploy common tools on top of your cluster

### ISSUE THREAD

**Issue by AsiaO1** [fuchicorp/main#638]
Please deploy common tools on top of your cluster and make sure all tools are deployed
and up and running. After you have deployed everything you can check is it up to verify

IsItUp link: https://isitup.fuchicorp.com/

Please watch this video:
https://academy.fuchicorp.com/videos/folders/watch/de409644e693eb3ca4386488164b1e3885efb0ba

**Comment by AsiaO1** [comment]
Hey there!
I left this ticket in Need Help because when I was setting up Jenkins I did not click on the "Grant" button. I later saw in the video that Farkhod was saying that it is important. So, I was wondering will I need to delete everything and start all over again, or the issue can be configured from elsewhere. 
Thanks in advance.

**Comment by ksalrin** [comment]
Hi Asia!
Have you tried accessing your Jenkins again?  I'm thinking its going to prompt you again and you should be able to select yes.  Please try and let me know if that is not the case.

**Comment by AsiaO1** [comment]
Hey Kelly, 
I tried. unfortunately, it is not prompting the question, it jumps straight to the dashboard. What do you suggest I should do?
