### ISSUE TITLE
7. DEPLOY RANCHER

### ISSUE THREAD

**Issue by Elyas09** [fuchicorp/main#641]
Deploy Rancher to your cluster. Please navigate to the common_tools repo and under charts 
you will find the Rancher helm chart:
https://github.com/fuchicorp/common_tools/tree/master/charts/rancher. 

Please follow this wiki to help deploy:
https://github.com/fuchicorp/common_tools/wiki/Deploying-Rancher-Chart

**Comment by Elyas09** [comment]
Succesfully deployed rancher

https://rancher.devopslearn.net/

![rancher2](https://user-images.githubusercontent.com/84156957/146691349-380ac69b-de78-44f0-8bc8-9f130b43833e.png)
![rancher](https://user-images.githubusercontent.com/84156957/146691350-91a3af6f-90b9-4118-a62c-aa5c7acdc763.png)

**Comment by ksalrin** [comment]
The cert does not seem to be showing up. Can you please take a look and troubleshoot.

**Comment by Elyas09** [comment]
Checked the values.yaml file. lets encrypt defined in the file.

![ticket7-cert-error1](https://user-images.githubusercontent.com/84156957/146864693-12f13b7d-1700-42eb-950b-f68365e34c91.png)

**Comment by Elyas09** [comment]
Checked the certificate with **kubectl -n cattle-system describe certificate**

![ticket7-cert-error2](https://user-images.githubusercontent.com/84156957/146865666-d194f388-453b-49fa-b081-729a00142674.png)

**Comment by Elyas09** [comment]
Used this link for troubleshooting. But not sure what the if the issue is with creating secret or the values.yaml file.

[https://rancher.com/docs/rancher/v2.5/en/installation/resources/troubleshooting/](url)

**Comment by Elyas09** [comment]
Checked the cert manager pod in tools namespace and found this error.

```
╭─Elyas09@bastion-fuchicorp-com ~/rancher 
╰─$ kubectl -n tools logs cert-manager-tools-6b465d9947-tr2g9 | grep -i error
E1221 06:05:52.303669       1 controller.go:158] cert-manager/controller/certificates-key-manager "msg"="re-queuing item due to error processing" "error"="Operation cannot be fulfilled on certificates.cert-manager.io \"tls-rancher-ingress\": the object has been modified; please apply your changes to the latest version and try again" "key"="cattle-system/tls-rancher-ingress" 
E1221 06:05:52.407894       1 controller.go:158] cert-manager/controller/certificaterequests-approver "msg"="re-queuing item due to error processing" "error"="Operation cannot be fulfilled on certificaterequests.cert-manager.io \"tls-rancher-ingress-2btqd\": the object has been modified; please apply your changes to the latest version and try again" "key"="cattle-system/tls-rancher-ingress-2btqd" 
```

**Comment by Elyas09** [comment]
Succesfully deployed rancher with certifications

https://rancher.devopslearn.net/

![rancher1](https://user-images.githubusercontent.com/84156957/147283865-0493bf91-4589-48f7-950b-2065f5e39fba.png)
