### ISSUE TITLE
6. ELK Deployment

### ISSUE THREAD

**Issue by Uulzhan** [fuchicorp/main#746]
Please deploy ELK to your cluster. You will find the source code located in the Elk-stack repo in FuchiCorp:
https://github.com/fuchicorp/elk-stack. 
Please follow the README.md to deploy: 
https://github.com/fuchicorp/elk-stack/blob/master/README.md .

Once you have deployed successfully, please add screenshots of both Kibana and Elastic-search to
the comments in your ticket for management approval.

**Comment by fsadykov** [comment]
Hello There,

Please add your question here or screenshot. I see the ticket is in the need of help column but I don't see any description of your issue 

Thank you
