### ISSUE TITLE
8. Bonus! Install Lens to local machine

### ISSUE THREAD

**Issue by Uulzhan** [fuchicorp/main#748]
Please install Lens to our local machine. Lens is a great tool to manage your cluster.
Please follow this wiki to start using the application:

https://github.com/fuchicorp/cluster-infrastructure/wiki/Lens-installation-to-local

**Comment by fsadykov** [comment]
Hello There,

Please add your question here or screenshot. I see the ticket is in the need of help column but I don't see any description of your issue 

Thank you
