### ISSUE TITLE
Update requirements PDF file

### ISSUE THREAD

**Issue by fuchicorp-manage** [fuchicorp/main#92]
Please mention following
1. If one of your instructors will assign a specific assignment if you are not able to finish for no reason you will be offboarded
2. If you are missing classes please DM  do not send message to the channel

**Comment by ksalrin** [comment]
I have updated the file and add to the google drive we share.  Please review Fuchicorp_Member_Guidelines_Updated.pdf.  Let me know if further edits are needed or if you cannot view the file. 

https://drive.google.com/drive/u/0/folders/1pW5UY-Zuqie_r8gHoXKuZy3Ph5RXZBTU
