### ISSUE TITLE
Clean up branches on all repos

### ISSUE THREAD

**Issue by fuchicorp-manage** [fuchicorp/main#93]
Hello team,

Please go over all repositories and make sure you delete branches that we don't use. Please make sure if the branch is in progress it should not be deleted. if someone has a ticket and working on that ticket please do not touch that branch. Please do research how we can delete branches automatically and do a demo 

Goal 
1. Keep repositories as clean as possible  
2. All future branches need to be deleted if we already finished the requests 

Thank you

**Comment by fsadykov** [comment]
You will need to upload your erros and description about your errors. Please do that before 5 pm call today so we can review it 

Thank you

**Comment by Indirka** [comment]
Deleting many branches at once:
git branch -r --merged | egrep -v "(^\*|master|dev)" | sed 's/origin\///' | xargs -n 1 git push origin --delete

**Comment by Indirka** [comment]
╭─Indirka@bastion-new-fuchicorp-com ~/cluster-infrastructure ‹master› 
╰─$ git branch -r --merged | egrep -v "(^\*|master|dev)" | sed 's/origin\///' | xargs -n 1 git push origin --delete
Warning: Permanently added the RSA host key for IP address '140.82.113.4' to the list of known hosts.
To git@github.com:fuchicorp/cluster-infrastructure.git
 - [deleted]         280
To git@github.com:fuchicorp/cluster-infrastructure.git
 - [deleted]         Adnankursun-patch-1
Warning: Permanently added the RSA host key for IP address '140.82.114.3' to the list of known hosts.
To git@github.com:fuchicorp/cluster-infrastructure.git
 - [deleted]         feature/#179
Warning: Permanently added the RSA host key for IP address '140.82.113.3' to the list of known hosts.
To git@github.com:fuchicorp/cluster-infrastructure.git
 - [deleted]         feature/#293
To git@github.com:fuchicorp/cluster-infrastructure.git
 - [deleted]         feature/100
To git@github.com:fuchicorp/cluster-infrastructure.git
 - [deleted]         feature/172
To git@github.com:fuchicorp/cluster-infrastructure.git
 - [deleted]         feature/175
error: unable to delete 'feature/282': remote ref does not exist
error: failed to push some refs to 'git@github.com:fuchicorp/cluster-infrastructure.git'
To git@github.com:fuchicorp/cluster-infrastructure.git
 - [deleted]         feature/354
To git@github.com:fuchicorp/cluster-infrastructure.git
 - [deleted]         feature/51
To git@github.com:fuchicorp/cluster-infrastructure.git
 - [deleted]         feature/disk-size
To git@github.com:fuchicorp/cluster-infrastructure.git
 - [deleted]         feature/tree
╭─Indirka@bastion-new-fuchicorp-com ~/cluster-infrastructure ‹master› 
[

**Comment by fsadykov** [comment]
based on @gulsenjm comments it turns out we can do clean up all branches

**Comment by gulsenjm** [comment]
Github has released a feature where anyone with admin permission to the repository can configure branches to get deleted automatically after pull requests are merged. Here are the steps -
Navigate to main page of the repository and click on Settings.
Under "Merge button", you can select or unselect "Automatically delete head branches" option.
This feature has been released by Github on July 31, 2019.

**Comment by gulsenjm** [comment]
https://stackoverflow.com/questions/14485936/automatically-delete-git-branch-after-merge-to-master
